UC-1607 database layer abstraction
ubirch/ubirch-client-go pull request #113
Opened 2023-01-18 12:23 UTC by leroxyl

2023-01-31 20:08 UTC, Carlos-Augusto requested changes
I am very satisfied to see how the sql details of the queries have been abstracted. Great job. I have however added a couple of comments. One of these related to a possible coupling of two concrete behaviors. Let me know what you think about this?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
> +		return dm.db.StoreExternalIdentity(ctx, StoreExternalIdentityParams(extId))
Does this mean that when on error you try one more time?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
> +	dm.dbConn.SetConnMaxLifetime(10 * time.Minute)
I am wondering why you have decided not to externalize these variables. Could they not better be expressed as configurable variables.

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
> +	dm.dbConn.SetConnMaxIdleTime(1 * time.Minute)
Maybe better expressed as config vars?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
> +			if pqErr.Code == "55P03" || // lock_not_available
I am wondering if these error handlers could be abstracted away. I mean, seems to me that they are very specific for each db type. It might make sense to abstract away these details. What do you think?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
>  				time.Sleep(10 * time.Millisecond)
Why do you need to sleep here?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/database_manager_test.go
> +	if fetchedId.Active != id.Active {
Can we improve the message? I am not sure what it really means or better what is expected.

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/db.go
> +package database
Provided that the service uses only one db at a time and not both. It seems to me that the behavior to use a switch case for every single function to select between the two dbs adds a tight coupling and might make it complicated for modifications. Additionally, some functions have implementation details for some cases. 
I am currently pondering if the code can be rearranged in a way that it mirrors more a factory method than a proxy/facade object and that these extra details be decoupled.

Here is one example:
```go
// Define an interface that defines the contract for creating objects
type Creator interface {
	Create(productType string) interface{}
}

// Define a concrete type that implements the Creator interface
type ConcreteCreator struct {}

func (cc ConcreteCreator) Create(productType string) interface{} {
	switch productType {
	case "product1":
		return &Product1{}
	case "product2":
		return &Product2{}
	default:
		return nil
	}
}

// Define a type that implements the product interface
type Product interface {
	DoSomething()
}

// Define two concrete types that implements the Product interface
type Product1 struct {}

func (p1 *Product1) DoSomething() {
	fmt.Println("Doing something with product 1")
}

type Product2 struct {}

func (p2 *Product2) DoSomething() {
	fmt.Println("Doing something with product 2")
}

// Client code that uses the Creator and Product interfaces
func main() {
	var creator Creator = ConcreteCreator{}
	product1 := creator.Create("product1").(Product)
	product2 := creator.Create("product2").(Product)
	product1.DoSomething()
	product2.DoSomething()
}
```
The idea is that assuming that the service only needs one type of db at a time. The basic initialization could be done for a particular db only based on a "selection parameter" (above "product1" or "product2"), which provide the ability to not have to be coupled to the switch logic and the concrete strategies.

Of course, it might be a bit more complicated than this example, but I think it might make your code even better for future maintenance. We can, as always, discuss. 

What do you think?

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/db.go
> +		// return db.sqlite.GetExternalIdentityUUIDs(ctx)
I think these comments should be removed

2023-01-31 20:08 UTC, Carlos-Augusto commented on main/adapters/database/db.go
> +		// convert UUIDs from string representation to uuid.UUID type
In a sense I think these specifics could be abstracted to the level of the specific db. They seem to be very related to a post processing needed because of the given driver. Below there are more of these behaviors.

2023-02-01 12:02 UTC, leroxyl commented on main/adapters/database/database_manager.go
> +		return dm.db.StoreExternalIdentity(ctx, StoreExternalIdentityParams(extId))
we try `maxRetries = 2` more times if the error is recoverable like `lock_not_available`, `too_many_connections` or `configuration_limit_exceeded`

2023-02-01 12:02 UTC, leroxyl commented on main/adapters/database/database_manager.go
> +	dm.dbConn.SetConnMaxLifetime(10 * time.Minute)
yes, done: https://github.com/ubirch/ubirch-client-go/commit/07a70b2cd0ea14d50a05a0f02d15d224ea58e2ae

2023-02-01 12:02 UTC, leroxyl commented on main/adapters/database/database_manager.go
> +	dm.dbConn.SetConnMaxIdleTime(1 * time.Minute)
same as above

2023-02-01 14:33 UTC, leroxyl commented on main/adapters/database/database_manager.go
> +			if pqErr.Code == "55P03" || // lock_not_available
yes, done: https://github.com/ubirch/ubirch-client-go/commit/6259d1cf80b22d39a316a9118a2afa99d43658c3

2023-02-01 14:34 UTC, leroxyl commented on main/adapters/database/database_manager.go
>  				time.Sleep(10 * time.Millisecond)
i think, because chances are, that after a short time, the lock or connection might be available again.

2023-02-01 14:35 UTC, leroxyl commented on main/adapters/database/database_manager_test.go
> +	if fetchedId.Active != id.Active {
I'm not sure, if I understand the question. This is an error message for unit tests.

2023-02-01 14:37 UTC, leroxyl commented on main/adapters/database/db.go
> +package database
yes, I like this very much. I followed the example and was able to get rid of all the ugly switch cases and it feels much cleaner now. thank you.
https://github.com/ubirch/ubirch-client-go/commit/f74ce5b8aa5710cfffd0c5bf6927deb87c89cf37

2023-02-01 14:38 UTC, leroxyl commented on main/adapters/database/db.go
> +		// return db.sqlite.GetExternalIdentityUUIDs(ctx)
done

2023-02-01 14:39 UTC, leroxyl commented on main/adapters/database/db.go
> +		// convert UUIDs from string representation to uuid.UUID type
this was resolved by the above mentioned refactoring https://github.com/ubirch/ubirch-client-go/commit/f74ce5b8aa5710cfffd0c5bf6927deb87c89cf37

2023-02-06 09:23 UTC, Carlos-Augusto commented on main/adapters/database/database_manager.go
> +		return dm.db.StoreExternalIdentity(ctx, StoreExternalIdentityParams(extId))
Thanks

2023-02-06 09:32 UTC, Carlos-Augusto commented on main/adapters/database/database_manager_test.go
> +	if fetchedId.Active != id.Active {
All good now. I get it now.

2023-02-07 09:59 UTC, Carlos-Augusto commented on main/adapters/database/db.go
> +package database
Thanks for having made the changes. It looks quite better now. Easier to follow and maintain.

2023-02-07 10:00 UTC, Carlos-Augusto approved these changes
LGTM

2023-02-07 10:01 UTC, merged